### ISSUE TITLE
What happened to the Mapstruction?

### ISSUE THREAD

**Issue by LiborSmolik** [mapstraction/mxn#318] opened 2015-01-09 11:14 UTC
The site is down for a few days now. 
The plugin on my website stopped working because of that (couldn't load mxn.js)
Anybody know what happened to them?

**Comment by codehaiku** [comment] 2015-01-11 23:51
Same here. Can't load MXN files. My website is broken for few days now. Any advice?

**Comment by mtmail** [comment] 2015-01-12 00:34
I emailed https://github.com/RandomEtc who seems to own the domain. He isn't listed in this project's contributors so he'd never see this issue. Can somebody also ping on https://twitter.com/RandomEtc as backup?

**Comment by ajturner** [comment] 2015-01-12 05:37
To clarify, what site and URL are you using for assets?

**Comment by vicchi** [comment] 2015-01-12 09:03
Tom (@RandomEtc) is still the domain owner and it doesn't expire 'till December 2015 according to a whois (thanks Tom!).

The domain is resolving to GitHub's page domain correctly ...

```
$ host mapstraction.com
mapstraction.com has address 207.97.227.245
mapstraction.com mail is handled by 0 mx2.sub3.homie.mail.dreamhost.com.
mapstraction.com mail is handled by 0 mx1.sub3.homie.mail.dreamhost.com.
$ host 207.97.227.245
245.227.97.207.in-addr.arpa domain name pointer pages.github.com.
```

... which would indicate a problem with the GitHub pages hosting. I'll try and take a look today.

**Comment by codehaiku** [comment] 2015-01-12 09:19
Hi vicchi. The problem is that the url for mxns are located in http://mapstraction.com domain which is down as of the moment. Is it possible to host the script manually?

Thanks

**Comment by vicchi** [comment] 2015-01-12 09:22
@codehaiku You can certainly host it on server space you have by cloning the main `mxn` repo ... but that still leaves stuff which depends on hosting under mapstraction.com broken. I'm looking at this right now.

**Comment by codehaiku** [comment] 2015-01-12 09:23
Thank you so much :)

**Comment by LiborSmolik** [comment] 2015-01-12 13:38
Great! I hope you sort this out guys!

**Comment by RandomEtc** [comment] 2015-01-12 17:32
I checked the registration. Set up for mapstraction.com has been the same for a long time. I own the domain but I point the name server to dreamhost, which is picked up by @ajturner's account I think?

If the only use of mapstraction.com is for github hosting then I can take back the name server settings and ensure that the CNAME/ANAME setup is correct: https://github.com/mapstraction/mapstraction.github.com/blob/master/CNAME

@ajturner @vicchi can you sanity check for me - is anyone using mapstraction.com for email, etc?

**Comment by vicchi** [comment] 2015-01-14 10:59
Hey Tom ... AFAIK there's no email use on the domain, though Andrew may know differently.

I think this may be linked to changes in GitHub's pages setup. I got this email in my Inbox this morning (apparently a follow up to an earlier mail that got lost in my spam filter)

```
Hi there mapstraction,

We wanted to follow-up on the email we sent back you in November about custom domains on GitHub Pages sites. To help us improve how we serve GitHub Pages, we’re deprecating our old GitHub Pages IP addresses.

The following domains owned by your account will be affected by this deprecation:

mapstraction.com (hosted at https://github.com/mapstraction/mapstraction.github.com)
Because your custom domain is pointed at a legacy IP, you’ll need to update your DNS configuration before February 2, 2015 to keep things running smoothly.

If you’re using a subdomain (coolthing.example.com, www.example.com, etc.), make sure you have a `CNAME` record that points to `mapstraction.github.io`.
If you’re not using a subdomain (example.com), make sure you have two `A` records set to the following IPs:
192.30.252.153
192.30.252.154
Questions? We’re here to help: https://github.com/contact. More information about these changes is also up on the GitHub blog: https://github.com/blog/1917-github-pages-legacy-ip-deprecation.
```

... looks like we need a DNS update here?

**Comment by vicchi** [comment] 2015-01-15 08:44
Everything seems to be working again ... @RandomEtc ... did you do a DNS update or was it a glitch in the GitHub matrix?

**Closed as completed by vicchi** 2015-01-15 08:44 UTC
Labels: bug, question

**Comment by RandomEtc** [comment] 2015-01-17 00:39
I didn't change anything. I think github is phasing this out slowly. Turning it off to shake out people who haven't updated.

I'm going to move DNS back to my registrar (@ajturner you can delete your mapstraction stuff from dreamhost) and update to the two A records above.

**Comment by RandomEtc** [comment] 2015-01-17 01:04
This is done. I don't know how long it will take to propagate, but mapstraction.com should resolve to whatever iwantmyname.com thinks the right IP addresses are.

**Comment by ajturner** [comment] 2015-01-17 11:25
Thanks @RandomEtc
