### ISSUE TITLE
Label Markers

### ISSUE THREAD

**Issue by icebergdelphi** [mapstraction/mxn#260] opened 2013-06-18 15:14 UTC
Does exist a way to create a Labels markers as next image? Thanks.

![recorrido](https://f.cloud.github.com/assets/3418905/669325/a7849b84-d829-11e2-9f84-4d1f6f63b05c.jpg)

**Comment by gilesc50** [comment] 2013-08-09 08:50
Hi - can you explain the question please?

**Comment by gilesc50** [comment] 2013-08-10 11:33
Ah I think this is a duplicate of request #276, so am closing this one.

**Closed as completed by gilesc50** 2013-08-10 11:33 UTC
